-- CreateTable
CREATE TABLE IF NOT EXISTS docket_quotation_threads (
    id SERIAL PRIMARY KEY,
    mysql_thread_id INT,
    thread_id VARCHAR(255) UNIQUE NOT NULL,
    mail_type VARCHAR(50) NOT NULL,
    docket_no VARCHAR(255),
    docket_status VARCHAR(100),
    state VARCHAR(100),
    is_gmd_client BOOLEAN DEFAULT FALSE,
    is_replied BOOLEAN DEFAULT FALSE,
    action_tag VARCHAR(100),
    match_reasons TEXT,
    date TIMESTAMP WITH TIME ZONE,
    sender VARCHAR(500),
    sender_details JSONB,
    to_details JSONB,
    cc_details JSONB,
    subject TEXT,
    body TEXT,
    body_preview TEXT,
    attach_names JSONB,
    attach_links JSONB,
    ocr_text TEXT,
    ai_summary TEXT,
    category VARCHAR(100),
    sub_category VARCHAR(100),
    company VARCHAR(100),
    codeword VARCHAR(100),
    user_labels JSONB,
    msg_count INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
